services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 5000:5000
    depends_on:
      postgres:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${PORT}/health" ]
      interval: 120s
      timeout: 5s
      retries: 10
      start_period: 30s # Wait 30 seconds before starting health checks
    environment:
      - DATABASE_URL=postgres://rungo:rungo@postgres:5432/rungo
      - PORT=5000
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=rungo
      - DATABASE_PASSWORD=rungo
      - DATABASE_NAME=rungo
    volumes:
      - ./:/app
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rungo
      - POSTGRES_USER=rungo
      - POSTGRES_PASSWORD=rungo
    ports:
      - "6543:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: rungo@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: rungo
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres-data:
  pgadmin-data:


