# stage one, build the app 
FROM node:20-alpine AS builder 

WORKDIR /app 

COPY  . .

RUN npm install 

RUN npm i @css-inline/css-inline-linux-arm64-musl

EXPOSE 5000


CMD [ "npm", "run", "start:dev" ]